#!/usr/bin/env python

import argparse
import logging

from gevent.server import StreamServer
from gateway import MockGateway

DEFAULT_GATEWAY_PORT = 2195

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Mock APNS Service")
    parser.add_argument('--debug', action='store_true', help='Print debug messages')
    parser.add_argument('--cert', type=str, required=True, help="Absolute path to the certificate file")
    parser.add_argument('--key', type=str, required=True, help="Absolute path to the private key file")
    parser.add_argument('--gatewayPort', type=int, default=DEFAULT_GATEWAY_PORT, help="The port where the server will be listening")

    args = parser.parse_args()

    log_level = 'DEBUG' if args.debug else 'INFO'
    logging.basicConfig(level=log_level)

    certPath = args.cert
    keyPath = args.key

    gateway = MockGateway()
    gatewayPort = args.gatewayPort
    gateway_server = StreamServer(('0.0.0.0', gatewayPort), gateway, keyfile=keyPath, certfile=certPath)

    try:
        logging.info("Starting APNS service listening on port %s" % gatewayPort)
        gateway_server.serve_forever()
    finally:
        logging.info("Shutting down")
        gateway_server.stop()
